services:
  elasticsearch:
    image: elasticsearch:8.16.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - http.cors.enabled=false
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.ml.max_model_memory_limit=2gb
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./src/resource/analysis:/usr/share/elasticsearch/config/analysis
    ports:
      - "9200:9200"
    networks:
      - esnet
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS http://localhost:9200/_cluster/health | grep -qE '(green|yellow)'" ]
      interval: 10s
      timeout: 5s
      retries: 20
  es-init:
    build: ./src/es-init
    container_name: es-initializer
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./src/resource:/resource
    command: [ "sh", "/resource/scripts/init.sh" ]
    restart: 'no'
    networks:
      - esnet
    extra_hosts:
      - "clearlaptop:192.168.1.198"
  kibana:
    image: kibana:8.16.0
    container_name: kibana
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - esnet
  headPlugin:
    image: 'mobz/elasticsearch-head:5'
    container_name: head
    ports:
      - '9100:9100'
    networks:
      - esnet
    
volumes:
  esdata1:
    driver: local

networks:
  esnet: