---
scheme: http
origins: ${scheme}://localhost:8080/
keycloak-port: 8080
keycloak-realm: NoteS
keycloak-host: localhost
keycloak-issuer: ${scheme}://${keycloak-host}:${keycloak-port}/realms/${keycloak-realm}
auth-props:
  issuers:
    - uri: ${keycloak-issuer}
      username-json-path: $.preferred_username
      claims:
        - jsonPath: $.realm_access.roles
        - jsonPath: $.resource_access.*.roles
server:
  port: 5267
  error:
    include-binding-errors: always
    include-message: always
  ssl:
    enabled: false
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: jdbc:postgresql://localhost:5432/NoteS_db
    driver-class-name: org.postgresql.Driver
    username: anyway
    password: anyway
    dbcp2:
      initial-size: 5
      max-total: 100
      max-idle: 30
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.format_sql: true
        hibernate.use_sql_comments: true
  elasticsearch:
    uris: http://clearlaptop:9200

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: accName:com.notes.models.api.account.AccName
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 2
    jaas:
      enabled: true
    listener:
      poll-timeout: 1800000
      concurrency: 1
      ack-mode: manual_immediate
  mvc:
    static-path-pattern: /resources/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer}

logging:
  level:
    com.notes.services.utils.com.notes.services.utils.Orchestrator: DEBUG
    org:
      springframework:
        web: DEBUG
        kafka: DEBUG
      hibernate: DEBUG
springdoc:
  swagger-ui:
    url: /resources/swagger.yaml
    syntax-highlight:
      activated: true
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: swager-api
      client-secret: VRwEkXlojgt5Jt2yv8b040EOBX73ijwt
      realm: ${keycloak-realm}
    csrf:
      enabled: true
sync-notes:
  strategy: single_task
---
scheme: https
keycloak-issuer: ${scheme}://${keycloak-host}:${keycloak-port}/realms/${keycloak-realm}
auth-props:
  issuers:
    - uri: ${keycloak-issuer}
      username-json-path: $.preferred_username
      claims:
        - jsonPath: $.realm_access.roles
        - jsonPath: $.resource_access.*.roles
server:
  error:
    include-binding-errors: always
    include-message: always
  ssl:
    enabled: true
spring:
  config:
    activate:
      on-profile: production
  datasource:
    jndi-name: jdbc/PostgressResourceTwisterDS
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    static-path-pattern: /resources/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer}
logging:
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
springdoc:
  swagger-ui:
    url: /resources/swagger.yaml
    syntax-highlight:
      activated: true
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: ${swagger-client-id}
      client-secret: ${swagger-keycloak-secret}
      realm: ${keycloak-realm}
    csrf:
      enabled: true