services: # https://stackoverflow.com/questions/69052692/right-way-to-configure-docker-compose-for-angular-apps
  app:
    build: .
    command: sh -c "npm start"
    ports:
      - "4200:4200"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules:
